POST http://localhost:3000/create-fitness/
Content-Type: application/json

{
    "programId":2,
    "programName":"Walk this Weigh"
}

###

PUT http://localhost:3000/edit-fitness/1/
Content-Type: application/json

{
    "programName":"Power Hour"
}

###

DELETE http://localhost:3000/delete-fitness/2/

###

POST http://localhost:3000/create-exercise/
Content-Type: application/json

{
    "exerciseId":2,
    "exerciseName":"Push-ups",
    "exerciseLengthInMinutes":10
}

###

DELETE http://localhost:3000/delete-exercise/2/